version: '3.8'
services:
  api-users:
    environment:
      - PORT=8000
    ports:
      - "8000:8000"

  api-notifications:
    environment:
      - PORT=8001
    ports:
      - "8001:8001"

  keycloak:
    ports:
      - "8080:8080"
